CentOS/centos-bootc

- .github/workflows/ci.yml
- .github/workflows/publish-image.yml
- .tekton/ostree-build.yaml
Let's assume for now that our own builder image isn't going to break us.  This is needed to unblock getting `git` in the image which we need for other things.
At some point yes we can investigate renovate for this potentially but I'd rather say that we have decent CI around the builder image.
> Unpin builder image

- docs/index.md
Simple docs change. It looks like a find/replace was done on sagano and the old naming explanation no longer applies to "centos-boot". Let's remove it before it confuses people.
> Removed the obsolete sagano name explanation and fixed FCOS URL.

- .github/workflows/ci.yml
- .github/workflows/publish-image.yml
This is important since it turns on some rpm-ostree reproducibility bits. TODO: replicate with RHTAP
> ci/github: Set SOURCE_DATE_EPOCH

- .github/workflows/ci.yml
- .github/workflows/publish-image.yml
Fedora ELN has a few bugs (e.g. the kernel dropped iptables support which breaks podman), we will also target c9s.
> Also build c9s

- docs/install.md
> docs/install: Fix cloud image link

- tier-0/initramfs.yaml
Just a small fix, adding a missing redirection so that '01-bootc-nohostonly.conf' is not created empty.
Since dracut's default is 'hostonly=no' this fix has no impact on the initramfs contents.
> Fix cat redirection

- .tekton/ostree-build.yaml
This was a copy-paste failure; we were intending to build ppc64le here.
> tekton: Fix duplicate s390x, use ppc64le

- tier-0/bootc-config.yaml
- tier-0/bootc.yaml
- tier-0/manifest.yaml
- tier-1/bootc-config.yaml
bootc isn't in C9S yet, but it is in the -dev images.  Add the install config unconditionally so that `bootc install` works in the `centos-bootc-dev` image.
> Always add bootc install config

- tier-0/initramfs.yaml
initramfs: Move our dracut config later
Our hostonly setting was conflicting with the default
`hostonly=yes` in `01-dist.conf`.
---
initramfs: Consolidate and rename drop-initramfs
No reason to have the "base" settings in distinct files.
---
> Dracut fixes

- tier-0/manifest.yaml
Prep for building with non-stream9 distros.
(TODO: add a dedicated variable for this at the toplevel)
> tier-0: bootc is only in eln

- tier-1/manifest.yaml
- tier-1/rpm-packaging.yaml
We need this to access RHEL RPM content today.
(I would like longer term to be able to fetch RPMs from registries
with a pull secret, xref https://github.com/coreos/rpm-ostree/issues/4155 )
> Add subscription-manager

- docs/builds.md
Since this is a complex tricky topic.
> docs: Add users and groups

- docs/example.ks
The partitioning defined in the example kickstart file suggests that the
installer supports hybrid boot. That's misleading and not true. Let's use
the `reqpart` kickstart command to automatically create partitions required
by the detected platform instead of creating all of them for all platforms.
**Note:** The `reqpart` command doesn't work with `bootloader --location=none` or
`bootloader --disabled`, so this change depends on the installer's support
for bootupd.
**Depends on:** https://github.com/rhinstaller/anaconda/pull/5298
> docs: Remove workarounds from example.ks

- docs/install.md
update docs to reflect changes from [containers/bootc #230 ](https://github.com/containers/bootc/pull/230) and[containers/bootc #226 ](https://github.com/containers/bootc/pull/226)
> update docs for bootc release 0.1.5

- tier-0/ostree.yaml
This turns on the functionality added in
https://github.com/ostreedev/ostree/pull/3114
> ostree: Enable root.transient = true by default

- tier-0/manifest.yaml
> tier-0: bootc is now in c9s

- fedora-eln.repo
- renovate.json
Renovate would identify new fedora eln compose and will raise a PR
> Fedora ELN compose as a dependency

- tier-0/autoupdates.yaml
- tier-0/manifest.yaml
- tier-1/autoupdates.yaml
This landed in https://github.com/containers/bootc/pull/179/commits/c13c9eb8dcd829db0b8d35a526ee7a0e9bc91e97 And we want to come out emphasizing it.
> Enable `bootc-fetch-apply-updates.service` by default

- docs/usage.md
There is some overlap with `install.md`, but that doc is all about how to just get started.
This doc aims to cover things that are somewhat different about the base image we ship here versus just what one might get from installing the same RPM packages.
The automatic updates being on by default is a big one.
> docs/usage: New doc

- docs/usage.md
I was a bit confused into thinking our `-dev` images had `root.transient` on, but they don't quite right now because we don't regenerate the initramfs after installing the updated ostree in that image.
However, because bootc-image-builder today is throwing away the immutable bit on `/` (a different bug, see
https://github.com/ostreedev/ostree/pull/3094 ) we actually... amazingly get a very similar effect in practice!
Anyways, let's go ahead and describe filesystem state here.
> usage: Describe filesystem semantics

- tier-0/ostree.yaml
Until https://github.com/osbuild/bootc-image-builder/issues/149 is fixed.
> tier-0: back off transient root

- catalog-info.yaml
Enable integration with a backstage based software catalog by adding the [backstage component descriptor file](https://backstage.io/docs/features/software-catalog/descriptor-format)
> chore: add backstage component descriptor file

- tier-1/initramfs-full.yaml
- tier-1/manifest.yaml
Right now we have an "allowlist" effectively for our dracut modules because we specify a configuration in `/usr/lib/dracut/dracut.conf.d` which seems to turn off autodetection.
Add in lvm which we definitely want to support.
> tier-1: Enable lvm dracut module

- docs/install.md
Let's link to the existing docs for using `bootc install to-disk` which fixes some bugs, though we aim to make bib a primary entrypoint for disks.
Second: Let's document using systemd credentials to inject a root SSH key, because this works across every image we ship where one can inject SMBIOS bits.  (But notably this doesn't work in most production IaaS virt systems like KubeVirt, AWS etc. which gets into cloud agents).
> docs/install: Doc direct bootc raw and systemd creds

- tier-1/rpm-packaging.yaml
This pulls in the code from https://github.com/openshift/os/pull/876/commits/dd35dd0e102aeed90df14f05c8ae9da4c8c5962a for the same reason.
> rpm-packaging: Add rhsm links

- tier-0/initramfs.yaml
Today it's built as a module for Fedora derivatives, but it's a relatively small kmod.
In particular I want to be able to use a virtiofs root as a bootstrap mechanism to generate disk images in a situation where we can't do nested containers, but we do have `/dev/kvm` - which is the setup we have in e.g. OpenShift Prow on `build02` with nested virt.
> initramfs: Add virtiofs

- tier-0/manifest.yaml
The systemd firstboot process does several things, but notably it runs a preset process.  This means that basically a plain `RUN systemctl enable foo` won't work unless you *also* write a preset file for it, and no one will know to do that.
Closes: https://github.com/CentOS/centos-bootc/issues/167
> Start with an empty `/etc/machine-id` to disable `ConditionFirstBoot`

- tier-1/initramfs-full.yaml
We want to support LUKS encrypted root filesystems in general.
We're shipping the code in the root, so we might as well enable
it in the initramfs.
---
> tier-1: Enable dracut crypt module too

- centos-bootc-config.json
- fedora-bootc-config.json
Pairs with https://github.com/containers/bootc/pull/299
This is intended to be the new canonical label for bootc-compatible images, as opposed to the existing `ostree.linux` etc.
> Add a `containers.bootc` label

- plans/main.fmf
It's a know issue and already has workaround
https://github.com/containers/podman/issues/16973
Comment out the line to not let it block the CI pipeline, since this part is just copied from a demo template.
> tmt: comment out the code in tmt plan which access to quay.io

- tier-0/basic-fixes.yaml
- tier-0/manifest.yaml
- tier-1/basic-fixes.yaml
The long-carried-forward patch to disable `tmp.mount` for RHEL rears its head again.
> tier-0: Enable tmp.mount by default

- .github/workflows/build-image.yml
- .tekton/ostree-build.yaml
- renovate.json
- It's not worth shipping around a distinct build container; bootc-image-builder already has all the dependencies we need since https://github.com/osbuild/bootc-image-builder/pull/176/commits/44d15acded8641499ea6b4c5d2acceb1bd9694b2
- I'd like to add a more first-class mechanism in bib to build base images
> build: Use bib

- centos-bootc-config.json
- fedora-bootc-config.json
This meshes with
<https://github.com/ostreedev/ostree/pull/3166/commits/f81b9fa1666c62a024d5ca0bbe876321f72529c7> in that our container image now behaves by default similarly to how the host works at runtime.
> Add `VOLUME /var` into container config by default

- tier-1/manifest.yaml
The `nfs-utils-coreos` package was created to not depend on Python mainly, but we are way deep into many other packages that do at this point.
There's some other package that `Requires: nfs-utils` that this should fix.
> Swap to nfs-utils, not nfs-utils-coreos

- centos-bootc-config.json
- fedora-bootc-config.json
This reverts commit 7966e8931bf282b3fc0eef0b7153fba7b789dc94. It just breaks derived builds across the board.
> Revert "Add `VOLUME /var` into container config by default"

- .tekton/testing-farm.yaml
bib team has tmt metadata define in this repo, in order to test the tmt code changes along with PR, we need to change the git ref.
> ci: override the GIT_URL & GIT_REF from SNAPSHOT

- docs/install.md
- Split into "local virt" and "production"
- Link to podman-bootc-cli
- Clean up, fix and inline kickstart example for readability
- Include bootc-image-builder in both local and production paths
> docs/install: Revamp

- centos-stream-9.yaml
On general principle, but specifically to enable transient root.
> c9s: Pull in latest bootc/ostree

- centos-stream-9.yaml
- copr-walters-fasttracks.repo
I'd REALLY resisted doing this for a long time, because it basically "forks" us from c9s.  However, the c9s "devel" composes are down to potentially *once a week* due to storage issues.
This one fast tracks https://kojihub.stream.centos.org/koji/buildinfo?buildID=59709
> Add a copr for fast tracks

- copr-walters-fasttracks.repo
- tier-0/ostree.yaml
c9s: Pull in latest bootc/ostree
On general principle, but specifically to enable transient root.
---
Enable transient (composefs) root (again)
This reverts commit 7977ead6e48c89706021aa1c867b5d3757ebeac6 and
effectively migrates the change from https://github.com/CentOS/centos-bootc-dev/pull/27/commits/8f5be0937144b602d8c1fdcaff4c51777b8cb254
to here.
See the linked PR for much more debate, but in a nutshell this
flips around a lot of tradeoffs around the filesystem layout
and will result in a much more easily explained state that
is intended to somewhat more closely match what happens with
a default `podman run --rm` invocation of the container.
Signed-off-by: Colin Walters <walters@verbum.org>
---
> Enable composefs root 

- README.md
- docs/builds.md
- docs/install.md
- docs/related.md
- docs/usage.md
I've copied (and slightly cleaned up) all the existing docs into a new dedicated git repository in
https://bootc-org.gitlab.io/documentation/
> docs: Link to new docs site

- tier-1/system-configuration.yaml
This is a relatively small shell script, and was already split out from cloud-init to support use cases like ours.
systemd-repart is a lot nicer but it isn't yet designed for our use case (root is not Discoverable Partition).
Also systemd-repart doesn't handle LVM which this script tries to support.
(IMO the real solution to stuff like this is either Stratis
or equivalent)
> system-configuration: Add cloud-utils-growpart

- tier-0/ostree.yaml
This is the opposite workaround for
https://github.com/ostreedev/ostree-rs-ext/issues/612
However, we still need to finally make `/opt` a directory to complete this, which currently wants changes in rpm-ostree. (Or, we could tweak our build process to inject as a container
afterwards)
> ostree: Switch to composefs enabled = yes

- tier-0/basic-fixes.yaml
As a followup for https://github.com/CentOS/centos-bootc/pull/371 this PR tweaks `tmpfiles.d/provision.conf` so
that there is only a single /var/roothome line for tmpfiles.d
As it is both provision.conf and rpm-ostree-0-integration.conf define the same dir.
This should fix https://github.com/containers/bootc/issues/358
> basic-fixes: Tweak basic-fixes: Tweak tmpfiles.d/provision.conf

- .github/workflows/build-image.yml
- Containerfile.centos-stream9
This is a small but notable step towards making the build process more container native.  The rpm-ostree bits are hidden much more.  At a high level, the build process outputs a "nested container" - a container image with a `/nested.ociarchive` at the top level.
Higher level build processes need not be aware of exactly how that `.ociarchive` is constructed (as it will definitely change in the future).
In an ideal world of course we wouldn't need this "wrapped image" as it runs the ergonomics.  See discussion in e.g. https://github.com/coreos/rpm-ostree/issues/4688
for that.
> ci: Add a Containerfile-based workflow

- centos-bootc-config.json
- fedora-bootc-config.json
Right now, the relationship between this image and bootc-image-builder is "floating".  However, we may want the ability to more strictly bind the two in the future.
With this, the bootc image links out to the recommended diskimage builder container, so automated tooling can find it instead of hardcoding it.
> Add a `bootc.diskimage-builder` label

- fedora-eln-bootc.yaml
- fedora-tier-0-40.yaml
- fedora-tier-0-rawhide.yaml
- fedora.repo
- Move eln to `fedora-eln-bootc` and use `fedora-bootc` for Fedora
- Add `fedora-tier-0-40` and `fedora-tier-0-rawhide` to build Fedora base images
- Add `fedora-devel` and `rawhide` repositories to `fedora.repo`
> Move eln to its own configs, add rawhide and devel to repos

- Containerfile.centos-stream10
- Containerfile.centos-stream9
- Containerfile.fedora-40
- The centos-stream9 one was removing the `.repo` files from the buildcontext, which is just wrong; we don't want to change the input git repo
- Use WORKDIR /src to simplify things
> build-sys: Sync Containerfiles
