CentOS/centos-bootc

centos-stream-9.yaml, fedora-tier-0-38.yaml, fedora-tier-0-dev-eln.yaml, fedora-tier-0-eln.yaml, fedora-tier-1-38.yaml, fedora-tier-1-eln.yaml, tier-0/bootc.yaml, tier-0/manifest.yaml
It exists now!
Since https://pagure.io/pungi-fedora/pull-request/1217 and https://github.com/minimization/content-resolver-input/pull/1006
=> Add bootc to eln

.github/workflows/ci.yml, .tekton/ostree-build.yaml
Needed to enable ELN, xref https://github.com/CentOS/sagano/pull/11
=> Use new builder image

docs/example.ks
We now have the static configs in bootupd, which significantly simplifies this.  Still need to land the Anaconda PR.
=> docs/example.ks: Update

tier-1/system-configuration.yaml
We expect to support this by default.
=> tier-1: Add lvm2

docs/builds.md
=> docs: Add a builds.md

docs/builds.md
I've started to put more content there.
=> docs: Link to existing example repo

docs/install.md
(I also pinned that and one other issue on that repo)
=> docs: Link a commonly hit issue

.tekton/centos-bootc-pull-request.yaml, .tekton/centos-bootc-push.yaml, .tekton/fedora-bootc-pull-request.yaml, .tekton/fedora-bootc-push.yaml
I still think that extracting the docs folder to its own repository will simplify the CI/CD code.
=> Don't trigger the pull request pipelines if docs files were changed

docs/builds.md
Since many if not most of our initial target use cases I think don't want this.
=> docs: Describe how to avoid home directory persistence

tier-0/autoupdates.yaml
Definitely a brown paper bag bug.
=> autoupdates: Fix to use correct unit

tier-0/autoupdates.yaml
Real motivation is to retrigger a build.
=> autoupdates: Minor comment cleanup

docs/builds.md
=> docs: Talk about ostree container commit

catalog-info.yaml
Included jira key, description, slack channel link and documentation link for backstage integration
=> chore: add more information for backstage integration

docs/usage.md
I added steps to move container image updates around with skopeo and apply them with bootc. Please double check that this is correc! It works really well on my side, but I'm unsure if bootc edit is a better option for changing where the update is pulled from.
=> Update usage.md for air-gapped & disconnected updates

.github/workflows/build-image.yml
This is a smaller version of https://github.com/CentOS/centos-bootc/pull/364
=> ci: Drop fedora:eln

tier-0/ostree.yaml
We want content lifecycled with the image.
Closes: https://github.com/CentOS/centos-bootc/issues/393
=> Add opt-usrlocal: root

README.md
Hopefully this re-triggers a container build.
=> README.md: Pointless change to try to retrigger container push

centos-bootc-config.json, fedora-bootc-config.json, tier-0/manifest.yaml
Closes: https://github.com/CentOS/centos-bootc/issues/449
=> Switch to systemd by default

tier-1/manifest.yaml
This got lost in the shuffling.
=> manifest: Add vim-minimal

centos-stream-common.yaml
=> Add dnf-yum
